name: NuGet Publish - ${{ env.MAIN_PROJECT }}

uses: ./_common.yml

on:
  push:
    branches: [ main ]  # Trigger on push to the main branch (adjust as needed)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # Workflow will run on Ubuntu virtual machines
    steps:
      - uses: actions/checkout@v3  # Checkout code from the repository

      - name: Use NuGet CLI
        uses: microsoft/setup-dotnet@v2  # Setup .NET environment
        with:
          dotnet-version: '>= 7.0'  # Specify desired .NET version

      - name: Restore dependencies
        run: |
            cd ${{ env.BASE_DIR }}${{ env.MAIN_PROJECT }}
            dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release ${{ env.MAIN_PROJECT }}.csproj  # Replace with your project path

      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v3  # Upload generated package as artifact
        with:
          name: nupkg

      - name: Deploy to GitHub Packages
        uses: Gr2m/github-actions-publish-package@v2  # Action to publish to GitHub Packages
        with:
          token: ${{ secrets.NUGET_API_KEY }}  # Access token with repo permission (stored as secret)
          file: ${{ secrets.ARTIFACT_PATH }}  # Path to uploaded artifact (from previous step)
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Optional, GitHub token for authentication (might not be needed)
