name: Publish NuGet Packages

on:
  workflow_dispatch:
    inputs:
      dotnet-version:
        description: '.NET'
        required: true
        default: '8.0'
        type: string
      target:
        description: 'Target'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - nuget
      projects:
        description: 'Comma-separated list of projects to pack (without .csproj extension). Leave empty to pack all projects.'
        required: false
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use NuGet CLI
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Create a temporary directory
        run: echo "TEMP_DIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Pack selected NuGet packages
        if: ${{ inputs.projects }}
        run: |
          IFS=',' read -ra SELECTED_PROJECTS <<< "${{ inputs.projects }}"
          for project in "${SELECTED_PROJECTS[@]}"; do
            dotnet pack "src/$project/$project.csproj" --configuration Release --output ${{ env.TEMP_DIR }}
          done

      - name: Find and pack all projects
        if: ${{ !inputs.projects }}
        run: |
          for project in $(find src -type f -name '*.csproj'); do
            dotnet pack "$project" --configuration Release --output ${{ env.TEMP_DIR }}
          done

      - name: Publish to GitHub Packages (using PAT)
        if: ${{ inputs.target == 'github' }}
        run: |
          cd ${{ env.TEMP_DIR }}
          dotnet nuget push *.nupkg -k ${{ secrets.GH_PACK_PAT }} -s https://nuget.pkg.github.com/Primyer/index.json

      - name: Publish to NuGet
        if: ${{ inputs.target == 'nuget' }}
        run: |
          cd ${{ env.TEMP_DIR }}
          dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
